const staticData = {
  houseOwnershipType: [
    "Own House",
    "Rented/Others",
    "Company Provided",
    "Parental House",
  ],
  employementType: [
    "Fulltime/Regular/Probationary",
    "Contractual/Part time",
    "Others",
  ],
  occupationType: [
    "Others",
    "Business in Trade sector",
    "State Govt Services",
    "Services In Public Sector Undertaking",
    "Services In Private Establishment",
    "Retired",
    "Business In Service sector",
    "Legal Profession",
    "Other Professionals",
    "Services In Defense Establishment",
    "Housewives",
    "CA/ICWA/Taxation/Finance",
    "Medical Profession",
    "Central Govt Services",
    "Artist/Writer Etc",
    "Engineering/Architect/Technical/Consultant",
    "Industrialist",
    "Artisan/Craftsman",
    "Migrant Laborers",
    "Students",
    "Share and Stock Broker",
    "Journalists",
  ],
  qualificationType: ["DEGREE", "HSC", "POST-GRADUATE", "DIPLOMA", "DOCTORATE"],
  liabilities: ["Yes", "No"],
  cities: [
    "Buffalo",
    "Rochester",

    "Los Angeles",
    "San Diego",
    "San Jose",

    "Chicago",
    "Aurora",
    "Rockford",

    "Houston",
    "San Antonio",
    "Dallas",

    "Philadelphia",
    "Pittsburgh",
    "Allentown",

    "Bethlehem",
    "Lancaster",
    "Harrisburg",
    "Altoona",

    "Phoenix",
    "Tucson",
    "Mesa",

    "Jacksonville",
    "Miami",
    "Tampa",
    "Orlando",

    "Indianapolis",
    "Fort Wayne",
    "Evansville",
  ],

  state: [
    "New York",
    "California",
    "Illinois",
    "Texas",
    "Pennsylvania",
    "Arizona",
    "Florida",
    "Indiana",
  ],
  netMonthlyIncome: [
    {
      value: "0-50,000",
      type: "netMnthIncom",
      isSelect: false,
      min: 0,
      max: 50000,
    },
    {
      value: "50,001-1,00,000",
      type: "netMnthIncom",
      isSelect: false,
      min: 5001,
      max: 100000,
    },
    {
      value: "1,00,001-2,00,000",
      type: "netMnthIncom",
      isSelect: false,
      min: 100001,
      max: 200000,
    },
    {
      value: "More than 2,00,000",
      type: "netMnthIncom",
      isSelect: false,
      min: 199999,
      max: 200000,
    },
  ],
  incomeDebtRatio: [
    {
      value: "Below 30%",
      type: "debtRatio",
      isSelect: false,
      min: "0%",
      max: "30.00%",
    },
    {
      value: "31%-40%",
      type: "debtRatio",
      isSelect: false,
      min: "31.00%",
      max: "40.00%",
    },
    {
      value: "41%-50%",
      type: "debtRatio",
      isSelect: false,
      min: "41.00%",
      max: "50.00%",
    },
    {
      value: "51%-60%",
      type: "debtRatio",
      isSelect: false,
      min: "51.00%",
      max: "60.00%",
    },
    {
      value: "61%-70%",
      type: "debtRatio",
      isSelect: false,
      min: "61.00%",
      max: "70.00%",
    },
    {
      value: "71%-80%",
      type: "debtRatio",
      isSelect: false,
      min: "71.00%",
      max: "80.00%",
    },
    {
      value: "81%-90%",
      type: "debtRatio",
      isSelect: false,
      min: "81%.00",
      max: "90%.00",
    },
    {
      value: "91%-100%",
      type: "debtRatio",
      isSelect: false,
      min: "91.00%",
      max: "100.00%",
    },
  ],
  ages: [
    {
      value: "Below 20 years",
      type: "Age",
      isSelect: false,
      min: 0,
      max: 20,
    },
    {
      value: "21 years-30 years",
      type: "Age",
      isSelect: false,
      min: 21,
      max: 30,
    },
    {
      value: "31 years-40 years",
      type: "Age",
      isSelect: false,
      min: 31,
      max: 40,
    },
    {
      value: "41 years-50 years",
      type: "Age",
      isSelect: false,
      min: 41,
      max: 50,
    },
    {
      value: "51 years-60 years",
      type: "Age",
      isSelect: false,
      min: 51,
      max: 60,
    },
    {
      value: "Above 60 years",
      type: "Age",
      isSelect: false,
      min: 59,
      max: 61,
    },
  ],
  repaymentType: [
    "Post Dated Cheques",
    "Check off",
    "Standing Instruction",
    "Cash",
    "ECS",
  ],
};

export default {
  staticData,
};
